### ISSUE TITLE
Using SSH protocol for DOCKER_HOST paramiko ssh issue

### ISSUE THREAD

**Issue by nodje** [tmaier/docker-compose#26]
Basically meeting this error when trying to `docker-compose up` on a DOCKER_HOST using SSH protocol:
```
Secsh channel 12 open FAILED: open failed: Connect failed
ERROR: for app_reverse-proxy_1  ChannelException(2, 'Connect failed')
ERROR: for reverse-proxy  ChannelException(2, 'Connect failed')
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 1077, in up
    to_attach = up(False)
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 1058, in up
    return self.project.up(
  File "/usr/lib/python3.8/site-packages/compose/project.py", line 571, in up
    results, errors = parallel.parallel_execute(
  File "/usr/lib/python3.8/site-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3.8/site-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3.8/site-packages/compose/project.py", line 554, in do
    return service.execute_convergence_plan(
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 568, in execute_convergence_plan
    return self._execute_convergence_start(
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 507, in _execute_convergence_start
    _, errors = parallel_execute(
  File "/usr/lib/python3.8/site-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3.8/site-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 509, in <lambda>
    lambda c: self.start_container_if_stopped(c, attach_logs=not detached, quiet=True),
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 621, in start_container_if_stopped
    return self.start_container(container)
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 626, in start_container
    container.start()
  File "/usr/lib/python3.8/site-packages/compose/container.py", line 241, in start
    return self.client.start(self.id, **options)
  File "/usr/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/docker/api/container.py", line 1094, in start
    res = self._post(url)
  File "/usr/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/docker/api/client.py", line 226, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/usr/lib/python3.8/site-packages/docker/transport/sshconn.py", line 32, in connect
    sock = self.ssh_transport.open_session()
  File "/usr/lib/python3.8/site-packages/paramiko/transport.py", line 875, in open_session
    return self.open_channel(
  File "/usr/lib/python3.8/site-packages/paramiko/transport.py", line 1017, in open_channel
    raise e
paramiko.ssh_exception.ChannelException: ChannelException(2, 'Connect failed')
```

I found this https://github.com/ParallelSSH/parallel-ssh/issues/49 refering to the issue, but apparently was fixed as early as 2016.
I doubt the paramiko version in use could be that old, but That's my only guess here.

PS: 
`docker-compose -f docker-compose-staging.yml pull` actually works, or at least doesn't issue any error.
this occurs on `docker-compose -f docker-compose-staging.yml up -d`

**Comment by tmaier** [comment]
Hi, I am not sure how the problem you mention is related to this docker image...

**Comment by nodje** [comment]
I'm not sure either, but it feels it's related to this image's python paramiko library.

I just double checked, the paramiko version is the latest available.

Could be something else but closing the issue anyway.
